### ISSUE TITLE
The application Friar Book has stoped unexplectedly.

### ISSUE THREAD

**Issue by neoscopio** [hanchang/Friar-Framework#1]
(process com.friarframework.)

Hi, I've tried to run the apk in virtualbox, from image x86 generic form http://www.android-x86.org

This emulation is android 2.2.1 with kernel 2.6.35.7-android-x86+root@afro#1

build: Master enf.20110220.000607 test-keys.

any hint?

tnx

**Comment by neoscopio** [comment]
Update: Tried on an android device (a low end chinese notebook) with android 2.2 and I've got the same result. 

I'm guessing this is becouse code is trying to get phone (device) information (unique identifier) and with this device and the emulation there is none.

**Comment by hanchang** [comment]
Hm, there were a couple of issues, sorry about that!

Android 2.2 was one problem issue; the friar.apk was compiled requiring 2.3+. I've since recompiled friar.apk to be Android 2.2 compatible.

There was also a bug where I left off a trailing slash in the example book's file path, that's been fixed as well.

Let me know if you run into any more issues, but please use the new URL at https://github.com/hanchang/friar/issues to report bugs. Best of luck, hope it works better for you!
